---
- name: Configuration et sécurisation des systèmes
  hosts: homelab_cluster,services,pi
  remote_user: "{{ ansible_user }}"

  roles:
    - SSH_Hardening
    - sysctl_config
    - fail2ban_install
