all:
  children:
    services:
      hosts:
        rocky:
          ansible_host: "{{ srv_rocky_ip }}"
    homelab_cluster:
      hosts:
        pve1:
          ansible_host: "{{ srv_pve1_ip }}" 
        pve2:
          ansible_host: "{{ srv_pve2_ip }}"
    pi:
      hosts:
        pi1:
          ansible_host: "{{ srv_pi1_ip }}"
